{{ if .Values.clair.enabled }}
# clair host isn't configurable yet.  this creates a service
# to get it working for now.
# see https://github.com/vmware/harbor/issues/3250
apiVersion: v1
kind: Service
metadata:
  name: {{ template "clair.fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 6060
  selector:
    name: {{ template "clair.fullname" . }}
{{ end }}