{{ if .Values.clair.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "clair.fullname" . }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/clair/clair-cm.yaml") . | sha256sum }}  
  labels:
    name: {{ template "clair.fullname" . }}
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ template "clair.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ template "clair.fullname" . }}
        release: {{ .Release.Name }}        
    spec:
      containers:
      - name: {{ template "clair.fullname" . }}
        image: {{ .Values.clair.image.repository }}:{{ .Values.clair.image.tag }}
        imagePullPolicy: {{ .Values.clair.image.pullPolicy }}
        args: ["-insecure-tls", "-config", "/config/config.yaml"]
        resources:
{{ toYaml .Values.clair.resources | indent 10 }}
        ports:
        - containerPort: 6060
        env:
{{ toYaml .Values.clair.env | indent 10 }}          
        volumeMounts:
        - name: clair-config
          mountPath: /config/config.yaml
          subPath: config.yaml
      volumes:
      - name: clair-config
        configMap:
          name: "{{ template "clair.fullname" . }}"
          items:
            - key: config.yaml
              path: config.yaml
{{ end }}