{{- if .Values.ingress.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Values.ingress.tls.secretName | quote }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.portus.tls.cert | b64enc | quote }}
  tls.key: {{ .Values.portus.tls.key | b64enc | quote }}
  ca.crt:  {{ .Values.portus.tls.cacert | b64enc | quote }}
{{- end }}